language: php

cache:
  directories:
    - "$HOME/.composer/cache"
    - vendor

php:
  - 7.4
  - 8.0

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --dev --no-interaction

script:
  - php vendor/bin/phpunit --coverage-clover build/coverage/xml